spring:
  application: 
    name: edu-admin
  profiles: 
    active: default
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        '[format_sql]': true
  h2:
   console:
      enabled: true
      path: /h2-console

server:
  port: 8081
       
logging:
  level:
    '[org.hibernate.SQL]': debug
