INSERT INTO COURSE (NAME) VALUES ('Lv3 Intensive Course');

INSERT INTO TRAINEE (ID, NAME) VALUES (1, 'Tim');
INSERT INTO TRAINEE (ID, NAME) VALUES (2, 'Mary');

INSERT INTO ATTENDANCE (COURSE_ID, TRAINEE_ID) VALUES (1, 1);
INSERT INTO ATTENDANCE (COURSE_ID, TRAINEE_ID) VALUES (1, 2);
