INSERT INTO TEAM (NAME) VALUES ('A');
INSERT INTO TEAM (NAME) VALUES ('B');

INSERT INTO MEMBER (NAME, TEAM_ID, ROLE) VALUES ('Tim', 1, 'ScrumMaster');
INSERT INTO MEMBER (NAME, TEAM_ID, ROLE) VALUES ('Mary', 1, 'Member');
