INSERT INTO TEAM (NAME) VALUES ('A');
INSERT INTO TEAM (NAME) VALUES ('B');

INSERT INTO MEMBER (NAME, TEAM_ID, ROLE, EMAIL, MOBILE) VALUES ('Tim', 1, 'ScrumMaster', 'tim@sk.com', '010-1234-0001');
INSERT INTO MEMBER (NAME, TEAM_ID, ROLE, EMAIL, MOBILE) VALUES ('Mary', 1, 'Member', 'mary@sk.com', '010-4321-0001');
